language: node_js
node_js:
  - "7"

install:
  - npm install

script:
  - npm run test:snyk
  - npm run lint
  - npm run build
  - npm run test:ci

after_success:
  - npm run test:coverage && npm run codecov

deploy:
  provider: script
  script: scripts/npm-publish.sh
  on:
    branch: master