language: node_js
node_js:
  - "7"

install:
  - npm install

script:
  - npm run test:snyk
  - npm run lint
  - npm run build
  - npm run test

after_success:
  - npm run test:coverage && npm run codecov

deploy:
  provider: script
  script: sh scripts/npm-publish.sh
  skip_cleanup: true
  on:
    tags: true
